version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: learning_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: learning
      MYSQL_USER: student
      MYSQL_PASSWORD: studentpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  postgres:
    image: postgres:15
    container_name: learning_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: learning
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/postgresql/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    container_name: learning_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - postgres

volumes:
  mysql_data:
  postgres_data:
